blank_issues_enabled: true
contact_links:
    - name: ONLY WEBSITE ISSUES HERE!!
      url: https://github.com/christianspecht/scm-backup/issues
      about: This is the repository for the SCM Backup *website*. Please create only issues for the website here. For the actual SCM Backup application, please create an issue in the main repository's issue tracker, https://github.com/christianspecht/scm-backup/issues